CREATE TABLE CUSTOMERS(ID INT PRIMARY KEY, NAME VARCHAR);
CREATE TABLE PRODUCTS(ID INT PRIMARY KEY, NAME VARCHAR, CODE VARCHAR, POINTS_COST INT);
CREATE TABLE ACTIVE_DAYS(ID INT PRIMARY KEY, CUSTOMER_ID INT, ACTIVE_DAYS INT, TOTAL_POINTS INT);

INSERT INTO PRODUCTS VALUES(1, 'Apple Smart Watch', 'AP567', 360);
INSERT INTO PRODUCTS VALUES(2, 'Hair Dryer', 'DR140', 300);
INSERT INTO PRODUCTS VALUES(3, 'Sun Glasses', 'QC101', 75);
INSERT INTO PRODUCTS VALUES(4, 'Gas Lamp', 'TM890', 150);
INSERT INTO PRODUCTS VALUES(5, 'Wireless Keyboard', 'KA502', 80);
INSERT INTO PRODUCTS VALUES(6, '120GB MicroSD', 'EP4500', 50);

INSERT INTO CUSTOMERS VALUES (1, 'Bill Johnson');
INSERT INTO CUSTOMERS VALUES (2, 'Sizwe Ngcobo');
INSERT INTO CUSTOMERS VALUES (3, 'Tumelo Mokoena');
INSERT INTO CUSTOMERS VALUES (4, 'Mohammed Naidoo');
INSERT INTO CUSTOMERS VALUES (5, 'Dakalo Maluleke');
 
 INSERT INTO ACTIVE_DAYS VALUES (1, 1, 500, 500);
INSERT INTO ACTIVE_DAYS VALUES (2, 4, 370, 370);
INSERT INTO ACTIVE_DAYS VALUES (3, 2, 54, 54);
INSERT INTO ACTIVE_DAYS VALUES (4, 5, 250, 250);
INSERT INTO ACTIVE_DAYS VALUES (5, 3, 20, 20);
