CREATE TABLE CUSTOMER(ID INT PRIMARY KEY, NAME VARCHAR);
CREATE TABLE PRODUCT(ID INT PRIMARY KEY, CODE VARCHAR, NAME VARCHAR, POINTS_COST INT);
CREATE TABLE ACTIVE_DAY(ID INT PRIMARY KEY, CUSTOMER_ID INT, ACTIVE_DAYS INT, TOTAL_POINTS INT);

INSERT INTO PRODUCT VALUES(1, 'AP567', 'Apple Smart Watch', 360);
INSERT INTO PRODUCT VALUES(2, 'DR140', 'Hair Dryer', 300);
INSERT INTO PRODUCT VALUES(3, 'QC101', 'Sun Glasses', 101);
INSERT INTO PRODUCT VALUES(4, 'TM890', 'Gas Lamp', 167);
INSERT INTO PRODUCT VALUES(5, 'KA502', 'Wireless Keyboard', 80);
INSERT INTO PRODUCT VALUES(6, 'EP4500', '120GB MicroSD', 40);


INSERT INTO CUSTOMER VALUES (1, 'Bill Johnson');
INSERT INTO CUSTOMER VALUES (2, 'Sizwe Ngcobo');
INSERT INTO CUSTOMER VALUES (3, 'Tumelo Mokoena');
INSERT INTO CUSTOMER VALUES (4, 'Mohammed Naidoo');
INSERT INTO CUSTOMER VALUES (5, 'Dakalo Maluleke');
 
 INSERT INTO ACTIVE_DAY VALUES (1,500, 1, 500);
INSERT INTO ACTIVE_DAY VALUES (2,370, 4, 370);
INSERT INTO ACTIVE_DAY VALUES (3,54,  2, 54);
INSERT INTO ACTIVE_DAY VALUES (4,250, 5, 250);
INSERT INTO ACTIVE_DAY VALUES (5,20, 3, 20);
